CREATE TABLE IF NOT EXISTS orders (
    id  BIGSERIAL PRIMARY KEY,
    number VARCHAR(150) UNIQUE NOT NULL,
    status TEXT CHECK (status in ( 'NEW', 'PROCESSING', 'INVALID', 'PROCESSED')),
    user_id BIGINT REFERENCES users(id) NOT NULL,
    accrual NUMERIC(15,2) DEFAULT 0 CHECK(accrual >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    upload_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);