CREATE TABLE IF NOT EXISTS user_balance (
    id  BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) UNIQUE NOT NULL,
    current NUMERIC(15,2) NOT NULL DEFAULT 0 CHECK(current >= 0),
    withdrawn NUMERIC(15,2) NOT NULL DEFAULT 0 CHECK(withdrawn >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);