CREATE TABLE IF NOT EXISTS withdrawals (
    id  BIGSERIAL PRIMARY KEY,
    order_number VARCHAR(150) UNIQUE NOT NULL,
    user_id BIGINT REFERENCES users(id)  NOT NULL,
    amount NUMERIC(15,2) NOT NULL CHECK(amount > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);