// Code generated by MockGen. DO NOT EDIT.
// Source: order.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	order "gophermarket/internal/app/domain/entity/order"
	order0 "gophermarket/internal/app/repositoriy/model/order"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockOrderRepository) GetAll(ctx context.Context, userID int) ([]order0.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, userID)
	ret0, _ := ret[0].([]order0.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockOrderRepositoryMockRecorder) GetAll(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockOrderRepository)(nil).GetAll), ctx, userID)
}

// GetByNumber mocks base method.
func (m *MockOrderRepository) GetByNumber(ctx context.Context, orderNumber string) (order0.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNumber", ctx, orderNumber)
	ret0, _ := ret[0].(order0.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNumber indicates an expected call of GetByNumber.
func (mr *MockOrderRepositoryMockRecorder) GetByNumber(ctx, orderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNumber", reflect.TypeOf((*MockOrderRepository)(nil).GetByNumber), ctx, orderNumber)
}

// GetNew mocks base method.
func (m *MockOrderRepository) GetNew(ctx context.Context) ([]order0.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNew", ctx)
	ret0, _ := ret[0].([]order0.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNew indicates an expected call of GetNew.
func (mr *MockOrderRepositoryMockRecorder) GetNew(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNew", reflect.TypeOf((*MockOrderRepository)(nil).GetNew), ctx)
}

// MakeAccrualToBalance mocks base method.
func (m *MockOrderRepository) MakeAccrualToBalance(ctx context.Context, order order0.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeAccrualToBalance", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakeAccrualToBalance indicates an expected call of MakeAccrualToBalance.
func (mr *MockOrderRepositoryMockRecorder) MakeAccrualToBalance(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeAccrualToBalance", reflect.TypeOf((*MockOrderRepository)(nil).MakeAccrualToBalance), ctx, order)
}

// Upload mocks base method.
func (m *MockOrderRepository) Upload(ctx context.Context, order order.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockOrderRepositoryMockRecorder) Upload(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockOrderRepository)(nil).Upload), ctx, order)
}
