// Code generated by MockGen. DO NOT EDIT.
// Source: withdrawal.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	withdrawal "gophermarket/internal/app/repositoriy/model/withdrawal"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWithdrawalRepository is a mock of WithdrawalRepository interface.
type MockWithdrawalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawalRepositoryMockRecorder
}

// MockWithdrawalRepositoryMockRecorder is the mock recorder for MockWithdrawalRepository.
type MockWithdrawalRepositoryMockRecorder struct {
	mock *MockWithdrawalRepository
}

// NewMockWithdrawalRepository creates a new mock instance.
func NewMockWithdrawalRepository(ctrl *gomock.Controller) *MockWithdrawalRepository {
	mock := &MockWithdrawalRepository{ctrl: ctrl}
	mock.recorder = &MockWithdrawalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawalRepository) EXPECT() *MockWithdrawalRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockWithdrawalRepository) Get(ctx context.Context, userID int) ([]withdrawal.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].([]withdrawal.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWithdrawalRepositoryMockRecorder) Get(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWithdrawalRepository)(nil).Get), ctx, userID)
}

// Make mocks base method.
func (m *MockWithdrawalRepository) Make(ctx context.Context, orderNum string, userID int, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", ctx, orderNum, userID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Make indicates an expected call of Make.
func (mr *MockWithdrawalRepositoryMockRecorder) Make(ctx, orderNum, userID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockWithdrawalRepository)(nil).Make), ctx, orderNum, userID, amount)
}
